tpm2-openssl: Fix build with OpenSSL 4.x
OpenSSL 4.0 completes the opaquing of struct asn1_string_st, so reaching
into ASN1_OCTET_STRING directly no longer compiles:

  src/tpm2-provider-pkey.c:152:53: error: incomplete definition of type
      'ASN1_OCTET_STRING' (aka 'struct asn1_string_st')
    152 |     if (Tss2_MU_TPM2B_PRIVATE_Unmarshal(tpk->privkey->data,
        |                                         ~~~~~~~~~~~~~^

Backport upstream commit 6dcc3b2 which switches tpm2_keydata_read() to
the ASN1_STRING_get0_data()/ASN1_STRING_length() accessors. 1.3.0 is
still the newest release, so there is no upgrade to take instead.

Signed-off-by: Khem Raj <khem.raj@oss.qualcomm.com>